language: elixir
elixir:
  - 1.7
  - 1.8
  - 1.9
  - 1.10
otp_release:
  - 20
  - 21
  - 22.3

matrix:
  include:
    - elixir: 1.10
      otp_release: 22.3
env:
  - MIX_ENV=test
script:
  - mix coveralls.json
after_script:
  - bash <(curl -s https://codecov.io/bash)
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
